# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-28 18:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homePageIntent', '0008_auto_20170128_1843'),
    ]

    operations = [
        migrations.AddField(
            model_name='moreinformation',
            name='publick',
            field=models.BooleanField(default=True),
        ),
    ]
