# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-28 17:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aboutPageIntent', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='historyofnckt',
            name='paragraphe',
            field=models.TextField(default=True),
            preserve_default=False,
        ),
    ]
