# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-28 18:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aboutPageIntent', '0003_historyofnckt_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='ourOrder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('avatar', models.CharField(max_length=50)),
                ('name', models.CharField(max_length=50)),
                ('descryption', models.TextField()),
            ],
        ),
    ]
