# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-29 04:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aboutPageIntent', '0004_ourorder'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vip',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('rank', models.CharField(max_length=70)),
                ('employment', models.CharField(max_length=70)),
                ('email', models.EmailField(max_length=254)),
                ('descryption', models.TextField()),
            ],
        ),
    ]
