# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-29 04:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aboutPageIntent', '0005_vip'),
    ]

    operations = [
        migrations.AddField(
            model_name='vip',
            name='range',
            field=models.SmallIntegerField(default=1, unique=True),
            preserve_default=False,
        ),
    ]
