# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-29 07:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aboutPageIntent', '0007_auto_20170129_1100'),
    ]

    operations = [
        migrations.AddField(
            model_name='vip',
            name='avatar',
            field=models.ImageField(blank=True, default=None, null=True, upload_to='vip_avatar'),
        ),
    ]
