# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-29 05:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aboutPageIntent', '0006_vip_range'),
    ]

    operations = [
        migrations.AddField(
            model_name='historyofnckt',
            name='publick',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='ourorder',
            name='publick',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='vip',
            name='publick',
            field=models.BooleanField(default=True),
        ),
    ]
