# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-27 06:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HelloGrid',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hello', models.CharField(max_length=30)),
                ('slogan', models.CharField(max_length=30)),
                ('firstAdd', models.CharField(max_length=50)),
                ('secondAdd', models.CharField(max_length=150)),
            ],
        ),
    ]
