# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-28 07:38
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('homePageIntent', '0006_rawtitle_rawside'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rawtitle',
            old_name='rawside',
            new_name='rawsideLeft',
        ),
    ]
