# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-29 05:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homePageIntent', '0009_moreinformation_publick'),
    ]

    operations = [
        migrations.AddField(
            model_name='spectrfach',
            name='publick',
            field=models.BooleanField(default=True),
        ),
    ]
