# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-02 18:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StudentInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('surname', models.CharField(max_length=50)),
                ('universety', models.CharField(max_length=100)),
                ('sex', models.BooleanField(default=True)),
            ],
        ),
    ]
