# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-06 12:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Student', '0003_studentinfo_root'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentinfo',
            name='age',
        ),
        migrations.RemoveField(
            model_name='studentinfo',
            name='root',
        ),
        migrations.RemoveField(
            model_name='studentinfo',
            name='sex',
        ),
        migrations.RemoveField(
            model_name='studentinfo',
            name='surname',
        ),
        migrations.RemoveField(
            model_name='studentinfo',
            name='universety',
        ),
        migrations.AddField(
            model_name='studentinfo',
            name='lat',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='studentinfo',
            name='lng',
            field=models.FileField(default=0, upload_to=''),
            preserve_default=False,
        ),
    ]
