# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-07 10:12
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Student', '0012_auto_20170207_1346'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentinfo',
            name='userid',
        ),
        migrations.AddField(
            model_name='studentinfo',
            name='user',
            field=models.OneToOneField(default=0, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='studentinfo',
            name='lat',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='studentinfo',
            name='lng',
            field=models.CharField(max_length=50),
        ),
    ]
