# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-28 06:45
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('homePageIntent', '0003_more_information'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='More_Information',
            new_name='MoreInformation',
        ),
    ]
