# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-28 07:06
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('homePageIntent', '0004_auto_20170128_1245'),
    ]

    operations = [
        migrations.CreateModel(
            name='RawInformation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('information', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='RawTitle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='homePageIntent.MoreInformation')),
            ],
        ),
        migrations.AddField(
            model_name='rawinformation',
            name='title',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='homePageIntent.RawTitle'),
        ),
    ]
