# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-28 07:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homePageIntent', '0005_auto_20170128_1306'),
    ]

    operations = [
        migrations.AddField(
            model_name='rawtitle',
            name='rawside',
            field=models.BooleanField(default=True),
            preserve_default=False,
        ),
    ]
