# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-28 12:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homePageIntent', '0007_auto_20170128_1338'),
    ]

    operations = [
        migrations.AlterField(
            model_name='spectrfach',
            name='avatar',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
